[features]
seeds = false
skip-lint = false
[programs.localnet]
wombat_solana = "C35VTXEEBrWAcQ3tCHh7x45ZRWLpu9KSQpTxfPHR8CYo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoangphuc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
